name: Build Windows EXE and Create Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Visual Studio Developer Command Prompt einrichten
      uses: ilammy/msvc-dev-cmd@v1

    - name: Projekt mit MSBuild bauen
      run: msbuild Matrix.sln /p:Configuration=Release

    - name: Gefundene EXE-Dateien auflisten
      run: cmd /c "dir /s /b *.exe"

    - name: EXE als Artefakt hochladen
      uses: actions/upload-artifact@v4
      with:
        name: Matrix-exe
        path: '**/bin/Release/*.exe'

    - name: Automatisch Tag erzeugen
      id: tagger
      shell: bash
      run: |
        TAG="auto-$(date +'%Y%m%d-%H%M%S')"
        echo "Generated TAG: $TAG"
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag "$TAG"
        git push origin "$TAG"
        echo "tag=$TAG" >> $GITHUB_ENV

    - name: Release erstellen
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.tag }}
        name: Release ${{ env.tag }}
        files: '**/bin/Release/*.exe'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
